class Naml < Formula
  desc "Convert Kubernetes YAML to Golang"
  homepage "https://github.com/krisnova/naml"
  url "https://github.com/krisnova/naml/archive/refs/tags/v1.0.3.tar.gz"
  sha256 "0842633268b06be82db4dd10c3c938f756f613c44c15c2d935b933409da8c4bd"
  license "Apache-2.0"
  head "https://github.com/krisnova/naml.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_ohos: "1b30718e3b5be83fcaacc8f455617a6c6f67df5e057e5d3d168ab0f8f09fb40a"
  end

  depends_on "go"

  def install
    ldflags = %W[
      -s -w
      -X github.com/kris-nova/naml.Version=#{version}
    ]

    system "go", "build", *std_go_args(ldflags:), "./cmd"
  end

  test do
    assert_match "Not Another Markup Language", shell_output("#{bin}/naml list")

    (testpath/"service.yaml").write <<~YAML
      apiVersion: v1
      kind: Namespace
      metadata:
        name: brewtest
    YAML

    assert_match "Application autogenerated from NAML v#{version}",
      pipe_output("#{bin}/naml codify", (testpath/"service.yaml").read)
  end
end
