class Scdoc < Formula
  desc "Small man page generator"
  homepage "https://sr.ht/~sircmpwn/scdoc/"
  url "http://ftp.debian.org/debian/pool/main/s/scdoc/scdoc_1.11.4.orig.tar.xz"
  sha256 "7732054b925fa526b852e028c6d992540a545cb8f893d583ae1f7fc84bd09b81"
  license "MIT"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_ohos: "cd4e456c84b37b107b15c88b9f4698aac14658775f882ed32737880a541d5555"
  end

  def install
    # scdoc sets by default LDFLAGS=-static which doesn't work on macos(x)
    system "make", "LDFLAGS=#{ENV.ldflags}", "PREFIX=#{prefix}"
    system "make", "install", "PREFIX=#{prefix}"
  end

  test do
    preamble = <<~EOF
      .\\" Generated by scdoc #{version}
      .\\" Complete documentation for this program is not available as a GNU info page
      .ie \\n(.g .ds Aq \\(aq
      .el       .ds Aq '
      .nh
      .ad l
      .\\" Begin generated content:
    EOF
    assert_equal preamble, pipe_output(bin/"scdoc", "")
  end
end
