class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.5.81.tar.gz"
  sha256 "8eafbd82fe31dc271667df21a33b943aecb2067d098f69bccb3f8693560cfdcc"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_ohos: "1bb566ed8a481e126f93b5f76c6b24c79221097b01acd1f17fb6a07d831f326b"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
