class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://github.com/astral-sh/uv/archive/refs/tags/0.12.7.tar.gz"
  sha256 "4a0941ef8f8131bf15f1dec50c96a17d94aae732ff8e9cb3a32c9d4f86d360fe"
  license any_of: ["Apache-2.0", "MIT"]
  compatibility_version 1
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_ohos: "7620bdcb58a6a3363765a6ccabfe6d347400767b7acfbe3cd2929534de9a85ae"
  end

  depends_on "cmake" => :build
  depends_on "pkgconf" => :build
  depends_on "rust" => :build
  depends_on "patchelf"
  depends_on "musl-compat"
  depends_on "openssl@3"

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  # ═══════════════════════════════════════════════════════════════════
  # HarmonyOS patches
  #
  # Problem: On HarmonyOS PC, the kernel refuses to dlopen an ELF without a
  # .codesign section, so downloaded Python interpreters and installed wheel
  # native modules must be code-signed.
  #
  #   0001: Skip ld --exec in musllinux detection
  #   0002: Skip ld --exec in libc detection
  #   0003: Vendored selfsign.rs (byte-identical to ohos-bst-light, kept in
  #         its own patch so it can be upgraded independently)
  #   0004: Adapt vendored selfsign.rs to an importable library
  #         (drop main(), export API)
  #   0005: Auto-sign wheel native modules on install (uv-install-wheel)
  #   0006: Auto-sign downloaded interpreters + disable bundled pip
  #   0007: Map HarmonyOS to linux (musllinux)
  # ═══════════════════════════════════════════════════════════════════

  patch do
    file "Patches/uv/0001-musllinux-skip-ld-exec.patch"
  end

  patch do
    file "Patches/uv/0002-libc-detect-skip-ld-exec.patch"
  end

  patch do
    file "Patches/uv/0003-vendor-selfsign-rs.patch"
  end

  patch do
    file "Patches/uv/0004-export-selfsign-lib.patch"
  end

  patch do
    file "Patches/uv/0005-autosign-wheels.patch"
  end

  patch do
    file "Patches/uv/0006-autosign-interpreters-and-disable-pip.patch"
  end

  patch do
    file "Patches/uv/0007-map-harmonyos-to-linux.patch"
  end

  def install
    # jitterentropy (vendored in aws-lc-sys) requires -O0; the compiler shim
    # strips -O flags from the build and appends its own level, overriding
    # CMake's per-file -O0 and tripping its #error. ENV.O0 pins the shim to -O0.
    ENV.O0

    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    # See: https://github.com/astral-sh/uv/issues/15401
    ENV["JEMALLOC_SYS_WITH_LG_PAGE"] = "16" if Hardware::CPU.arm? && OS.linux?

    # jemalloc is unbuildable on OHOS.
    system "cargo", "install", *std_cargo_args(path: "crates/uv"), "--no-default-features"

    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  def caveats
    <<~EOS
      uv resolves OHOS as linux-musl (musllinux), so both the Python
      interpreters it downloads and the binary wheels it installs are musl
      builds. Every ELF is auto-signed on install, so downloaded
      interpreters and native modules work normally.

      Interpreters still come from astral-sh/python-build-standalone (uv's
      default source); on OHOS downloads prefer the Chinese mirror
      https://registry.npmmirror.com/-/binary/python-build-standalone and
      fall back to the official mirror / GitHub automatically.

      Wheels come from PyPI, uv's default index. Change the index with
      `uv pip install --index-url ...` or `export UV_DEFAULT_INDEX=...`.

      The pip bundled inside uv-downloaded interpreters is disabled
      (`python -m pip` fails loudly): pip-installed wheels would bypass uv's
      auto-signing. Use `uv add` or `uv pip install` instead.
    EOS
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}/uvx -q ruff@0.5.1 --version")
  end
end
