class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://github.com/astral-sh/uv/archive/refs/tags/0.12.5.tar.gz"
  sha256 "e349c9eb85876921895330f6fee5f01f109d5ec06dcd3b475fb7b4b8de75eac6"
  license any_of: ["Apache-2.0", "MIT"]
  head "https://github.com/astral-sh/uv.git", branch: "main"
  revision 7

  livecheck do
    url :stable
    strategy :github_latest
  end

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_ohos: "ce39dc6ea372c50893bdd0f3926bdd9522863c445c17a8cc64e0acf68ce6882a"
  end

  depends_on "cmake" => :build
  depends_on "ohos-sdk" => :build
  depends_on "pkgconf" => :build
  depends_on "rust" => :build
  depends_on "python@3.14"
  depends_on "patchelf"
  depends_on "musl-compat"
  depends_on "openssl@3"

  # ═══════════════════════════════════════════════════════════════════
  # HarmonyOS patches
  #
  # Problem: On HarmonyOS PC, the kernel refuses to dlopen an ELF without a
  # .codesign section (noexec filesystem), so downloaded Python interpreters
  # and installed wheel native modules must be code-signed.
  #
  #   0001: Skip ld --exec in musllinux detection
  #   0002: Skip ld --exec in libc detection
  #   0003: Vendored selfsign.rs (byte-identical to ohos-bst-light, kept in
  #         its own patch so it can be upgraded independently)
  #   0004: Adapt vendored selfsign.rs to an importable library
  #         (drop main(), export API)
  #   0005: Auto-sign wheel native modules on install (uv-install-wheel)
  #   0006: Auto-sign downloaded interpreters + disable bundled pip
  #   0007: Map HarmonyOS to linux (musllinux)
  # ═══════════════════════════════════════════════════════════════════

  patch do
    file "Patches/uv/0001-musllinux-skip-ld-exec.patch"
  end

  patch do
    file "Patches/uv/0002-libc-detect-skip-ld-exec.patch"
  end

  patch do
    file "Patches/uv/0003-vendor-selfsign-rs.patch"
  end

  patch do
    file "Patches/uv/0004-export-selfsign-lib.patch"
  end

  patch do
    file "Patches/uv/0005-autosign-wheels.patch"
  end

  patch do
    file "Patches/uv/0006-autosign-interpreters-and-disable-pip.patch"
  end

  patch do
    file "Patches/uv/0007-map-harmonyos-to-linux.patch"
  end

  def install
    # aws-lc-sys only finds its CMake toolchain path on this target; must be
    # the keg root, build.rs appends native/.
    ENV["OHOS_NDK_HOME"] = formula_opt_prefix("ohos-sdk")

    # jemalloc is unbuildable on this target.
    system "cargo", "install", "--no-default-features", *std_cargo_args(path: "crates/uv")

    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  def caveats
    <<~EOS
      uv resolves OHOS as linux-musl (musllinux), so both the Python
      interpreters it downloads and the binary wheels it installs are musl
      builds. Every ELF is auto-signed on install, so downloaded
      interpreters and native modules work normally.

      Interpreters still come from astral-sh/python-build-standalone (uv's
      default source); on OHOS downloads prefer the Chinese mirror
      https://registry.npmmirror.com/-/binary/python-build-standalone and
      fall back to the official mirror / GitHub automatically.

      Wheels come from PyPI, uv's default index. Change the index with
      `uv pip install --index-url ...` or `UV_DEFAULT_INDEX=...`.

      The pip bundled inside uv-downloaded interpreters is disabled
      (`python -m pip` fails loudly): pip-installed wheels would bypass uv's
      auto-signing. Use `uv add` (preferred) or `uv pip install` instead.
    EOS
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    system bin/"uv", "venv", "--python", formula_opt_bin("python@3.14")/"python3.14", "test-venv"
    system bin/"uv", "pip", "install", "--python", "test-venv/bin/python", "requests"
    py = testpath/"test-venv/bin/python"
    assert_match "requests", shell_output("#{py} -c \"import requests; print('requests', requests.__version__)\"")
  end
end
