class Libsecret < Formula
  desc "Library for storing/retrieving passwords and other secrets"
  homepage "https://wiki.gnome.org/Projects/Libsecret"
  url "https://download.gnome.org/sources/libsecret/0.21/libsecret-0.21.7.tar.xz"
  sha256 "6b452e4750590a2b5617adc40026f28d2f4903de15f1250e1d1c40bfd68ed55e"
  # Excluding GPL-2.0-or-later and Apache-2.0 which are for tests
  license "LGPL-2.1-or-later"
  compatibility_version 1

  # libsecret doesn't use GNOME's "even-numbered minor is stable" version
  # scheme. This regex is the same as the one generated by the `Gnome` strategy
  # but it's necessary to avoid the related version scheme logic.
  livecheck do
    url :stable
    regex(/libsecret[._-]v?(\d+(?:\.\d+)+)\.t/i)
  end

  bottle do
    root_url "https://atomgit.com/social4hyq/homebrew-core/releases/download/libsecret-v0.21.7-r1"
    sha256 cellar: :any_skip_relocation, arm64_ohos: "c0f6ee93e7484166823d71a9e460b96c35b051b2343f47cdde9bf1b64222659b"
  end

  depends_on "docbook-xsl" => :build
  depends_on "gettext" => :build
  depends_on "gobject-introspection" => :build
  depends_on "libxslt" => :build
  depends_on "meson" => :build
  depends_on "ninja" => :build
  depends_on "pkgconf" => [:build, :test]
  depends_on "expat"
  depends_on "glib"
  depends_on "libgcrypt"

  def install
    ENV["XML_CATALOG_FILES"] = "#{etc}/xml/catalog"

    # tool/secret-tool.c's one call to getpass() doesn't just need a
    # prototype -- OHOS's musl doesn't export the symbol at all (this tap's
    # build sysroot linker error: "undefined symbol: getpass"; a plain
    # extern declaration compiles but fails at the final link step). It's
    # not in musl-compat's ~36-symbol shim list either, and pulling in a
    # whole extra runtime dependency for one legacy BSD call in a CLI tool
    # isn't worth it, so replace the call site with a minimal termios-based
    # reimplementation (disable echo, read a line, restore echo).
    getpass_impl = <<~C
      static char *
      ohos_getpass (const char *prompt)
      {
        static char buf[256];
        struct termios old_term, new_term;
        int restore = 0;
        size_t len;

        fputs (prompt, stderr);
        fflush (stderr);

        if (tcgetattr (STDIN_FILENO, &old_term) == 0) {
          new_term = old_term;
          new_term.c_lflag &= ~ECHO;
          if (tcsetattr (STDIN_FILENO, TCSAFLUSH, &new_term) == 0)
            restore = 1;
        }

        if (!fgets (buf, sizeof (buf), stdin))
          buf[0] = '\\0';

        if (restore)
          tcsetattr (STDIN_FILENO, TCSAFLUSH, &old_term);

        fputc ('\\n', stderr);

        len = strlen (buf);
        if (len > 0 && buf[len - 1] == '\\n')
          buf[len - 1] = '\\0';

        return buf;
      }

    C

    inreplace "tool/secret-tool.c",
              "#include <string.h>\n\n#define SECRET_ALIAS_PREFIX",
              "#include <string.h>\n#include <stdio.h>\n#include <termios.h>\n#include <unistd.h>\n\n" \
              "#define SECRET_ALIAS_PREFIX"

    read_password_tty_old = "static SecretValue *\nread_password_tty (void)\n{\n\tgchar *password;\n\n" \
                            "\tpassword = getpass (\"Password: \");\n"
    read_password_tty_new = "#{getpass_impl}static SecretValue *\nread_password_tty (void)\n" \
                            "{\n\tgchar *password;\n\n\tpassword = ohos_getpass (\"Password: \");\n"
    # Plain inreplace(old, new) runs new through String#gsub, where a
    # literal "\0"/"\n" in the replacement is a regex back-reference, not a
    # literal backslash -- and getpass_impl is full of those (char literals
    # like '\0'). Substitute on the raw string with a block instead so the
    # replacement text is inserted verbatim.
    inreplace "tool/secret-tool.c" do |s|
      replaced = s.inreplace_string.sub!(read_password_tty_old) { read_password_tty_new }
      odie "libsecret: read_password_tty patch anchor not found" if replaced.nil?
    end

    # No vala in this tap: skip generating the .vapi (Vala bindings aren't
    # consumed by anything this tap ports).
    system "meson", "setup", "build", "-Dbashcompdir=#{bash_completion}",
                                      "-Dgtk_doc=false",
                                      "-Dvapi=false",
                                      *std_meson_args
    system "meson", "compile", "-C", "build", "--verbose"
    system "meson", "install", "-C", "build"
  end

  test do
    (testpath/"test.c").write <<~C
      #include <libsecret/secret.h>

      const SecretSchema * example_get_schema (void) G_GNUC_CONST;

      const SecretSchema *
      example_get_schema (void)
      {
          static const SecretSchema the_schema = {
              "org.example.Password", SECRET_SCHEMA_NONE,
              {
                  {  "number", SECRET_SCHEMA_ATTRIBUTE_INTEGER },
                  {  "string", SECRET_SCHEMA_ATTRIBUTE_STRING },
                  {  "even", SECRET_SCHEMA_ATTRIBUTE_BOOLEAN },
                  {  "NULL", 0 },
              }
          };
          return &the_schema;
      }

      int main()
      {
          example_get_schema();
          return 0;
      }
    C

    flags = shell_output("pkgconf --cflags --libs libsecret-1").chomp.split
    system ENV.cc, "test.c", "-o", "test", *flags
    system "./test"
  end
end
