class LldAT21 < Formula
  desc "LLVM Project Linker"
  homepage "https://lld.llvm.org/"
  url "https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.8/llvm-project-21.1.8.src.tar.xz"
  sha256 "4633a23617fa31a3ea51242586ea7fb1da7140e426bd62fc164261fe036aa142"
  # The LLVM Project is under the Apache License v2.0 with LLVM Exceptions
  license "Apache-2.0" => { with: "LLVM-exception" }
  compatibility_version 1

  livecheck do
    formula "llvm@21"
  end

  keg_only :versioned_formula

  depends_on "cmake" => :build
  depends_on "llvm@21"
  depends_on "zstd"

  on_linux do
    depends_on "zlib-ng-compat"
  end

  # OHOS code signing: adds a `.codesign` section to every ELF this linker
  # produces, defaulting the equivalent of --code-sign to ON (every
  # executable ELF on OHOS must carry one to run). Touches lld/ELF/* only —
  # llvm@21 doesn't build lld at all, hence this being a separate formula.
  patch do
    file "Patches/lld@21/0001-ohos-code-sign.patch"
  end

  def install
    rpaths = [rpath]
    rpaths << formula_opt_lib("llvm@21").to_s if OS.linux?

    cmake_args = %W[
      -DBUILD_SHARED_LIBS=ON
      -DCMAKE_INSTALL_RPATH=#{rpaths.join(";")}
      -DLLD_BUILT_STANDALONE=ON
      -DLLD_VENDOR=#{tap&.user}
      -DLLVM_CMAKE_DIR=#{formula_opt_lib("llvm@21")}/cmake/llvm
      -DLLVM_ENABLE_LTO=ON
      -DLLVM_INCLUDE_TESTS=OFF
      -DLLVM_USE_SYMLINKS=ON
    ]

    # llvm@21's libLLVM.so was built with OHOS's default TLS codegen
    # (-femulated-tls: llvm::parallel::threadIndex is exported as
    # __emutls_v.../__emutls_t..., not a real TLS symbol). This standalone
    # LLD build links against that dylib but doesn't inherit its TLS
    # codegen choice from anywhere (LLVMConfig.cmake doesn't re-export raw
    # compiler flags) — without forcing the same choice here, LLD's own
    # object files emit real ELF TLS relocations for the same symbol, and
    # `ld.lld`/`liblldELF.so` fail at load time with "symbol not found:
    # _ZN4llvm8parallel11threadIndexE" (real-TLS mangling, absent from a
    # dylib that only exports the emulated-TLS variant).
    if OS.linux?
      cmake_args << "-DCMAKE_C_FLAGS=-femulated-tls"
      cmake_args << "-DCMAKE_CXX_FLAGS=-femulated-tls"
    end

    system "cmake", "-S", "lld", "-B", "build", *cmake_args, *std_cmake_args
    system "cmake", "--build", "build"
    system "cmake", "--install", "build"
  end

  def post_install
    return unless OS.linux?

    # Generate cc/c++ shims (moved here from llvm@21's post_install now that
    # clang and lld are split across two formulas — this needs both present,
    # and lld@21 depends_on "llvm@21" guarantees clang is already installed
    # by the time this runs). --code-sign is this formula's patch's default,
    # so links through these shims are auto-signed with no flag needed.
    llvm = Formula["llvm@21"]
    shim_ld_library_path = [
      formula_opt_lib("zstd").to_s,
      formula_opt_lib("zlib-ng-compat").to_s,
      llvm.opt_lib.to_s,
    ].join(":")

    shims = { "cc" => "clang", "c++" => "clang++" }
    shims.each do |shim_name, target|
      shim_path = HOMEBREW_PREFIX/"bin"/shim_name
      File.write(shim_path, <<~SH)
        #!/bin/sh
        # Auto-generated by lld@21 post_install. Edits will be lost on reinstall.
        # --code-sign is LLD's default, so links are auto-signed — no flag needed.
        # ld.lld isn't co-located with clang any more (separate formula) —
        # put this keg's bin/ on PATH so clang's driver finds *this*
        # (codesign-patched) ld.lld instead of an unsigned fallback.
        export PATH="#{opt_bin}:$PATH"
        export LD_LIBRARY_PATH="#{shim_ld_library_path}:$LD_LIBRARY_PATH"
        exec "#{llvm.opt_bin}/#{target}" "$@"
      SH
      shim_path.chmod(0755)
    end

    ohai "Generated cc/c++ shims in #{HOMEBREW_PREFIX}/bin (LD_LIBRARY_PATH only; --code-sign is LLD default)"
  end

  test do
    if OS.linux?
      # llvm@21 is keg-only and its bin/clang can lose the HOMEBREW_PREFIX/bin
      # symlink race to ohos-sdk's own bundled clang (see the llvm@21 formula's
      # caveats). ENV.cc below must be *this* keg's clang, not whatever
      # ohos-sdk's older, differently-configured driver happens to occupy —
      # the -fuse-ld= PATH-priority check just below depends on it.
      llvm = Formula["llvm@21"]
      ENV["CC"] = (llvm.opt_bin/"clang").to_s
      ENV["CXX"] = (llvm.opt_bin/"clang++").to_s
    end

    assert_match(/LLD 21\./, shell_output("#{bin}/wasm-ld --version"))

    (testpath/"bin/lld").write <<~SHELL
      #!/bin/bash
      exit 1
    SHELL
    chmod "+x", "bin/lld"

    (testpath/"bin").install_symlink "lld" => "ld64.lld"
    (testpath/"bin").install_symlink "lld" => "ld.lld"

    (testpath/"test.c").write <<~C
      #include <stdio.h>
      int main() {
        printf("hello, world!");
        return 0;
      }
    C

    error_message = case ENV.compiler
    when /^gcc(-\d+)?$/ then "ld returned 1 exit status"
    when :clang then "linker command failed"
    else odie "unexpected compiler"
    end

    # Check that the `-fuse-ld=lld` flag actually picks up LLD from PATH.
    ENV.prepend_path "PATH", bin
    with_env(PATH: "#{testpath}/bin:#{ENV["PATH"]}") do
      assert_match error_message, shell_output("#{ENV.cc} -v -fuse-ld=lld test.c 2>&1", 1)
    end

    system ENV.cc, "-v", "-fuse-ld=lld", "test.c", "-o", "test"
    assert_match "hello, world!", shell_output("./test")

    # OHOS: the whole point of this formula's patch — code-sign should be on
    # by default (no --code-sign flag passed) and go away with --no-code-sign.
    if OS.linux?
      readelf = formula_opt_bin("llvm@21")/"llvm-readelf"

      system ENV.cc, "-fuse-ld=lld", "test.c", "-o", "test-signed"
      assert_match ".codesign", shell_output("#{readelf} -S test-signed")

      system ENV.cc, "-fuse-ld=lld", "-Wl,--no-code-sign", "test.c", "-o", "test-unsigned"
      refute_match ".codesign", shell_output("#{readelf} -S test-unsigned")
    end
  end
end
