class Typeshare < Formula
  desc "Synchronize type definitions between Rust and other languages for seamless FFI"
  homepage "https://github.com/1Password/typeshare"
  url "https://github.com/1Password/typeshare/archive/refs/tags/v1.13.4.tar.gz"
  sha256 "7a929012e1f2a4e07616dd769e049adbb5aebae9faf0776f6268a0673281dd78"
  license any_of: ["Apache-2.0", "MIT"]
  head "https://github.com/1Password/typeshare.git", branch: "main"

  livecheck do
    url :stable
    regex(/^v?(\d+(?:\.\d+)+)$/i)
  end

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_ohos: "f9cb478cf6c12045fba90af85455fdddcfd1ef4655a0c22a0d89f3fb884bcffa"
  end

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args(path: "cli")

    generate_completions_from_executable(bin/"typeshare", "completions")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/typeshare --version")

    system bin/"typeshare", "--generate-config", testpath
    assert_path_exists testpath/"typeshare.toml"

    (testpath/"example.rs").write <<~RUST
      #[typeshare]
      struct MyStruct {
          my_name: String,
          my_age: u32,
      }
    RUST

    system bin/"typeshare", testpath/"example.rs", "--lang", "typescript", "--output-file", testpath/"TestType.ts"
    assert_match "Generated by typeshare", (testpath/"TestType.ts").read
  end
end
